/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhojava;

/**
 *
 * @author Jean
 */
public class PedidosPizza extends javax.swing.JPanel {

    /**
     * Creates new form PedidosPizza
     */
    public PedidosPizza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telefoneTF = new javax.swing.JTextField();
        telefoneL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        clienteTabelModel = new javax.swing.JTable();
        addB = new javax.swing.JButton();
        delB = new javax.swing.JButton();
        salvarBT1 = new javax.swing.JButton();
        addB1 = new javax.swing.JButton();

        telefoneTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneTFActionPerformed(evt);
            }
        });

        telefoneL.setText("Telefone:");

        clienteTabelModel.setModel(clienteTableModel);
        clienteTabelModel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteTabelModelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(clienteTabelModel);

        addB.setText("+");
        addB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBActionPerformed(evt);
            }
        });

        delB.setText("-");
        delB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBActionPerformed(evt);
            }
        });

        salvarBT1.setText("Pesquisar");
        salvarBT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBT1ActionPerformed(evt);
            }
        });

        addB1.setText("Editar");
        addB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addB1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(telefoneL)
                        .addGap(18, 18, 18)
                        .addComponent(telefoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salvarBT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneL)
                    .addComponent(salvarBT1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addB1)
                        .addGap(9, 9, 9)
                        .addComponent(delB))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(158, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void telefoneTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneTFActionPerformed

    private void clienteTabelModelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteTabelModelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteTabelModelMouseClicked

    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed
            // Abrir tela para personalização do pedido
            
    }//GEN-LAST:event_addBActionPerformed

    private void delBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delBActionPerformed

    private void salvarBT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBT1ActionPerformed
        String nomePesquisa = telefoneTF.getText().trim();
    //Pedidos cliente
    }//GEN-LAST:event_salvarBT1ActionPerformed

    private void addB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addB1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addB;
    private javax.swing.JButton addB1;
    private javax.swing.JTable clienteTabelModel;
    private javax.swing.JButton delB;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton salvarBT1;
    private javax.swing.JLabel telefoneL;
    private javax.swing.JTextField telefoneTF;
    // End of variables declaration//GEN-END:variables
}
