/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhojava;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Claudia
 */
public class Pizzaria extends javax.swing.JFrame {

    private int linhaClicada = -1;
    private final ClienteTableModel clienteTableModel;
    private final SaborTableModel saborTableModel;
    /**
     * Creates new form Pizzaria
     */
    public Pizzaria() {
        clienteTableModel = new ClienteTableModel();
        saborTableModel = new SaborTableModel();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPizzaria = new javax.swing.JTabbedPane();
        guiaCliente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();
        btnListarCliente = new javax.swing.JButton();
        btnLimparCliente = new javax.swing.JButton();
        btnExcluirCliente = new javax.swing.JButton();
        lbNomeCliente = new javax.swing.JLabel();
        edtNomeCliente = new javax.swing.JTextField();
        lbSobrenomeCliente = new javax.swing.JLabel();
        edtSobrenomeCliente = new javax.swing.JTextField();
        lbTelefoneCliente = new javax.swing.JLabel();
        edtTelefoneCliente = new javax.swing.JFormattedTextField();
        btnInserirCliente = new javax.swing.JButton();
        btnAtualizarCliente = new javax.swing.JButton();
        guiaSabores = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCadastrarSabor = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaSabor = new javax.swing.JTable();
        btnListarSabor = new javax.swing.JButton();
        btnLimparSabor = new javax.swing.JButton();
        btnExcluirSabor = new javax.swing.JButton();
        lbNomeCliente1 = new javax.swing.JLabel();
        edtNomeCliente1 = new javax.swing.JTextField();
        lbSobrenomeCliente1 = new javax.swing.JLabel();
        lbTelefoneCliente1 = new javax.swing.JLabel();
        edtNomeCliente2 = new javax.swing.JTextField();
        guiaPreço = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tiposPizzaP = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        valorCmTF = new javax.swing.JTextField();
        confirmaB = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        painelListarPedidos = new javax.swing.JPanel();
        lbSelecionarVeiculoVender = new javax.swing.JLabel();
        guiaPedido = new javax.swing.JPanel();
        lbSelecioneCliente = new javax.swing.JLabel();
        comboSelecionaCliente = new javax.swing.JComboBox();
        lbPorVeiculo = new javax.swing.JLabel();
        btnFiltrarCliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPedidos = new javax.swing.JTable();
        btnLocar = new javax.swing.JButton();
        btnInserirPedido = new javax.swing.JButton();
        btnAtualizarPedido = new javax.swing.JButton();
        lbSelecioneCliente1 = new javax.swing.JLabel();
        btnAdicionarPizza = new javax.swing.JButton();
        edtPesqCliente = new javax.swing.JFormattedTextField();
        btnPesqCliente = new javax.swing.JButton();
        lbNomeClientePesq = new javax.swing.JLabel();
        edtNomeClientePesq = new javax.swing.JTextField();
        lbCPFClientePesq = new javax.swing.JLabel();
        edtTelefoneClientePesq = new javax.swing.JFormattedTextField();
        edtSobrenomeClientePesq = new javax.swing.JTextField();
        lbSobrenomeClientePesq = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaCliente.setModel(clienteTableModel);
        jScrollPane1.setViewportView(tabelaCliente);

        btnListarCliente.setText("Listar");
        btnListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarClienteActionPerformed(evt);
            }
        });

        btnLimparCliente.setText("Limpar");
        btnLimparCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparClienteActionPerformed(evt);
            }
        });

        btnExcluirCliente.setText("Excluir");
        btnExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirClienteActionPerformed(evt);
            }
        });

        lbNomeCliente.setText("Nome:");

        lbSobrenomeCliente.setText("Sobrenome:");

        lbTelefoneCliente.setText("Telefone:");

        try {
            edtTelefoneCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edtTelefoneCliente.setText("");

        btnInserirCliente.setText("Inserir");
        btnInserirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirClienteActionPerformed(evt);
            }
        });

        btnAtualizarCliente.setText("Atualizar");
        btnAtualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout guiaClienteLayout = new javax.swing.GroupLayout(guiaCliente);
        guiaCliente.setLayout(guiaClienteLayout);
        guiaClienteLayout.setHorizontalGroup(
            guiaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaClienteLayout.createSequentialGroup()
                .addGroup(guiaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guiaClienteLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnInserirCliente)
                        .addGap(46, 46, 46)
                        .addComponent(btnAtualizarCliente))
                    .addGroup(guiaClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(guiaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(guiaClienteLayout.createSequentialGroup()
                                .addGroup(guiaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(guiaClienteLayout.createSequentialGroup()
                                        .addComponent(btnListarCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnLimparCliente))
                                    .addGroup(guiaClienteLayout.createSequentialGroup()
                                        .addComponent(lbNomeCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(edtNomeCliente)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(guiaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExcluirCliente)
                                    .addGroup(guiaClienteLayout.createSequentialGroup()
                                        .addComponent(lbSobrenomeCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(edtSobrenomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(guiaClienteLayout.createSequentialGroup()
                                .addComponent(lbTelefoneCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edtTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        guiaClienteLayout.setVerticalGroup(
            guiaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(guiaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarCliente)
                    .addComponent(btnLimparCliente)
                    .addComponent(btnExcluirCliente))
                .addGap(18, 18, 18)
                .addGroup(guiaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeCliente)
                    .addComponent(edtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSobrenomeCliente)
                    .addComponent(edtSobrenomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guiaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefoneCliente)
                    .addComponent(edtTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(guiaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserirCliente)
                    .addComponent(btnAtualizarCliente))
                .addGap(40, 40, 40))
        );

        painelPizzaria.addTab("Cliente", guiaCliente);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cadastrar Sabor");

        btnCadastrarSabor.setText("Inserir");
        btnCadastrarSabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarSaborActionPerformed(evt);
            }
        });

        tabelaSabor.setModel(clienteTableModel);
        jScrollPane3.setViewportView(tabelaSabor);

        btnListarSabor.setText("Listar");
        btnListarSabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarSaborActionPerformed(evt);
            }
        });

        btnLimparSabor.setText("Limpar");
        btnLimparSabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparSaborActionPerformed(evt);
            }
        });

        btnExcluirSabor.setText("Excluir");
        btnExcluirSabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirSaborActionPerformed(evt);
            }
        });

        lbNomeCliente1.setText("Nome:");

        lbSobrenomeCliente1.setText("Tipo:");

        lbTelefoneCliente1.setText("Preço:");

        javax.swing.GroupLayout guiaSaboresLayout = new javax.swing.GroupLayout(guiaSabores);
        guiaSabores.setLayout(guiaSaboresLayout);
        guiaSaboresLayout.setHorizontalGroup(
            guiaSaboresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaSaboresLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(guiaSaboresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(guiaSaboresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guiaSaboresLayout.createSequentialGroup()
                        .addComponent(btnCadastrarSabor)
                        .addGap(666, 666, 666))
                    .addGroup(guiaSaboresLayout.createSequentialGroup()
                        .addGroup(guiaSaboresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(guiaSaboresLayout.createSequentialGroup()
                                .addGroup(guiaSaboresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(guiaSaboresLayout.createSequentialGroup()
                                        .addComponent(btnListarSabor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnLimparSabor))
                                    .addGroup(guiaSaboresLayout.createSequentialGroup()
                                        .addComponent(lbNomeCliente1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(edtNomeCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(guiaSaboresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExcluirSabor)
                                    .addComponent(lbSobrenomeCliente1)))
                            .addGroup(guiaSaboresLayout.createSequentialGroup()
                                .addComponent(lbTelefoneCliente1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtNomeCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(305, 305, 305))))
        );
        guiaSaboresLayout.setVerticalGroup(
            guiaSaboresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaSaboresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(guiaSaboresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarSabor)
                    .addComponent(btnLimparSabor)
                    .addComponent(btnExcluirSabor))
                .addGap(18, 18, 18)
                .addGroup(guiaSaboresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeCliente1)
                    .addComponent(edtNomeCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSobrenomeCliente1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guiaSaboresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefoneCliente1)
                    .addComponent(edtNomeCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarSabor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        painelPizzaria.addTab("Cadastrar Sabores", guiaSabores);

        jRadioButton3.setText("Premium");

        jRadioButton2.setText("Especial");

        jRadioButton1.setText("Simples");

        jLabel4.setText("Tipos de pizza:");

        javax.swing.GroupLayout tiposPizzaPLayout = new javax.swing.GroupLayout(tiposPizzaP);
        tiposPizzaP.setLayout(tiposPizzaPLayout);
        tiposPizzaPLayout.setHorizontalGroup(
            tiposPizzaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tiposPizzaPLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        tiposPizzaPLayout.setVerticalGroup(
            tiposPizzaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tiposPizzaPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tiposPizzaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel4))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel5.setText("Valor cm²:");

        valorCmTF.setText("Valor");

        confirmaB.setText("Confirmar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tiposPizzaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valorCmTF, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(confirmaB))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tiposPizzaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(valorCmTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmaB))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Cadastrar Preço");

        javax.swing.GroupLayout guiaPreçoLayout = new javax.swing.GroupLayout(guiaPreço);
        guiaPreço.setLayout(guiaPreçoLayout);
        guiaPreçoLayout.setHorizontalGroup(
            guiaPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaPreçoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(guiaPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(292, Short.MAX_VALUE))
        );
        guiaPreçoLayout.setVerticalGroup(
            guiaPreçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaPreçoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        painelPizzaria.addTab("Cadastrar Preço", guiaPreço);

        lbSelecionarVeiculoVender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSelecionarVeiculoVender.setText("Pedidos");

        javax.swing.GroupLayout painelListarPedidosLayout = new javax.swing.GroupLayout(painelListarPedidos);
        painelListarPedidos.setLayout(painelListarPedidosLayout);
        painelListarPedidosLayout.setHorizontalGroup(
            painelListarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelListarPedidosLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lbSelecionarVeiculoVender)
                .addContainerGap(589, Short.MAX_VALUE))
        );
        painelListarPedidosLayout.setVerticalGroup(
            painelListarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelListarPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSelecionarVeiculoVender, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(341, Short.MAX_VALUE))
        );

        painelPizzaria.addTab("Listar Pedidos", painelListarPedidos);

        lbSelecioneCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSelecioneCliente.setText("Pedidos");

        comboSelecionaCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Telefone" }));
        comboSelecionaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboSelecionaClienteMouseClicked(evt);
            }
        });

        lbPorVeiculo.setText("Por:");

        btnFiltrarCliente.setText("Filtrar");
        btnFiltrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarClienteActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(tabelaPedidos);

        btnLocar.setText("Locar");
        btnLocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocarActionPerformed(evt);
            }
        });

        btnInserirPedido.setText("Novo Pedido");
        btnInserirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirPedidoActionPerformed(evt);
            }
        });

        btnAtualizarPedido.setText("Atualizar Pedido");

        lbSelecioneCliente1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSelecioneCliente1.setText("Selecione o cliente");

        btnAdicionarPizza.setText("Adicionar Pizza");

        btnPesqCliente.setText("Pesquisar");
        btnPesqCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqClienteActionPerformed(evt);
            }
        });

        lbNomeClientePesq.setText("Nome:");

        lbCPFClientePesq.setText("Telefone:");

        try {
            edtTelefoneClientePesq.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbSobrenomeClientePesq.setText("Sobrenome:");

        javax.swing.GroupLayout guiaPedidoLayout = new javax.swing.GroupLayout(guiaPedido);
        guiaPedido.setLayout(guiaPedidoLayout);
        guiaPedidoLayout.setHorizontalGroup(
            guiaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaPedidoLayout.createSequentialGroup()
                .addGroup(guiaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guiaPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbPorVeiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboSelecionaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(edtPesqCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesqCliente))
                    .addGroup(guiaPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(guiaPedidoLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnInserirPedido)
                        .addGap(35, 35, 35)
                        .addComponent(btnAtualizarPedido)
                        .addGap(27, 27, 27)
                        .addComponent(btnAdicionarPizza))
                    .addGroup(guiaPedidoLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(btnLocar))
                    .addGroup(guiaPedidoLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lbSelecioneCliente)
                        .addGap(313, 313, 313)
                        .addComponent(btnFiltrarCliente))
                    .addGroup(guiaPedidoLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lbSelecioneCliente1))
                    .addGroup(guiaPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(guiaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSobrenomeClientePesq)
                            .addComponent(lbNomeClientePesq))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(guiaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(guiaPedidoLayout.createSequentialGroup()
                                .addComponent(edtNomeClientePesq, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbCPFClientePesq)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtTelefoneClientePesq, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(edtSobrenomeClientePesq, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        guiaPedidoLayout.setVerticalGroup(
            guiaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaPedidoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lbSelecioneCliente1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(guiaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboSelecionaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPorVeiculo)
                    .addComponent(edtPesqCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesqCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guiaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeClientePesq)
                    .addComponent(edtNomeClientePesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCPFClientePesq)
                    .addComponent(edtTelefoneClientePesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(guiaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSobrenomeClientePesq)
                    .addComponent(edtSobrenomeClientePesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(guiaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guiaPedidoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(lbSelecioneCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(guiaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInserirPedido)
                            .addComponent(btnAtualizarPedido)
                            .addComponent(btnAdicionarPizza))
                        .addGap(18, 18, 18)
                        .addComponent(btnLocar))
                    .addGroup(guiaPedidoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnFiltrarCliente)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        painelPizzaria.addTab("Pedido Pizza", guiaPedido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPizzaria, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(painelPizzaria, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarClienteActionPerformed
        try {
            ClienteDAO dao = new ClienteDAO();
            clienteTableModel.setListaCliente(dao.listar());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Erro ao listar clientes.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnListarClienteActionPerformed

    private void btnLimparClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparClienteActionPerformed
        clienteTableModel.limpaTabela();
    }//GEN-LAST:event_btnLimparClienteActionPerformed

    private void btnExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirClienteActionPerformed
        try {
            ClienteDAO dao = new ClienteDAO();
            int[] linhasSelecionadas = tabelaCliente.getSelectedRows();
            List<Cliente> listaExcluir = new ArrayList();
            for (int i = 0; i < linhasSelecionadas.length; i++) {
                Cliente cliente = clienteTableModel.getCliente(linhasSelecionadas[i]);
                dao.remover(cliente);
                listaExcluir.add(cliente);
            }
            for(Cliente cliente:listaExcluir){
                clienteTableModel.removeCliente(cliente);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Erro ao realizar exclusão de cliente(s).", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirClienteActionPerformed

    private void btnInserirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirClienteActionPerformed
        String nome = edtNomeCliente.getText();
        String sobrenome = edtSobrenomeCliente.getText();
        String telefone = edtTelefoneCliente.getText();
       
        Cliente cliente = new Cliente(nome, sobrenome, telefone);
        try {
            ClienteDAO dao = new ClienteDAO();
            dao.cadastrar(cliente);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Erro ao inserir cliente no banco de dados. E="+ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        clienteTableModel.adicionaCliente(cliente);
    }//GEN-LAST:event_btnInserirClienteActionPerformed

    private void btnAtualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarClienteActionPerformed
        linhaClicada = tabelaCliente.getSelectedRow();
        if(linhaClicada!=-1){
            Cliente cliente = clienteTableModel.getCliente(linhaClicada);
            int cod = (int) clienteTableModel.getValueAt(linhaClicada, 0);
            cliente.setNome(edtNomeCliente.getText());
            cliente.setSobrenome(edtSobrenomeCliente.getText());
            cliente.setTelefone(edtTelefoneCliente.getText());
            cliente.setId(cod);
            ClienteDAO dao = null;
            try {
                dao = new ClienteDAO();
                dao.alterar(cliente);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"Erro ao atualizar cliente no banco de dados. E="+ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
            clienteTableModel.fireTableRowsUpdated(linhaClicada, linhaClicada);
        }
    }//GEN-LAST:event_btnAtualizarClienteActionPerformed

    private void btnCadastrarSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarSaborActionPerformed

    }//GEN-LAST:event_btnCadastrarSaborActionPerformed

    private void btnLocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocarActionPerformed

    }//GEN-LAST:event_btnLocarActionPerformed

    private void btnFiltrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarClienteActionPerformed

    }//GEN-LAST:event_btnFiltrarClienteActionPerformed

    private void comboSelecionaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboSelecionaClienteMouseClicked
      
    }//GEN-LAST:event_comboSelecionaClienteMouseClicked

    private void btnInserirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInserirPedidoActionPerformed

    private void btnPesqClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqClienteActionPerformed
        Cliente result = new Cliente();
        String pesq = edtPesqCliente.getText().toUpperCase();
        ClienteDAO dao = new ClienteDAO();
        if (comboSelecionaCliente.getSelectedItem().toString() == "Telefone")
            result = dao.pesquisarTelefone(pesq);
        edtNomeClientePesq.setText(result.getNome());
        edtSobrenomeClientePesq.setText(result.getSobrenome());
        edtTelefoneClientePesq.setText(result.getTelefone());
                
    }//GEN-LAST:event_btnPesqClienteActionPerformed

    private void btnListarSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarSaborActionPerformed
         try {
            SaborDAO dao = new SaborDAO();
            saborTableModel.setListaSabor(dao.listar());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Erro ao listar sabores.", "Erro", JOptionPane.ERROR_MESSAGE);
        }       
    }//GEN-LAST:event_btnListarSaborActionPerformed

    private void btnLimparSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparSaborActionPerformed
        saborTableModel.limpaTabela();
    }//GEN-LAST:event_btnLimparSaborActionPerformed

    private void btnExcluirSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirSaborActionPerformed
        try {
            SaborDAO dao = new SaborDAO();
            int[] linhasSelecionadas = tabelaCliente.getSelectedRows();
            List<Sabor> listaExcluir = new ArrayList();
            for (int i = 0; i < linhasSelecionadas.length; i++) {
                Sabor sabor = saborTableModel.getSabor(linhasSelecionadas[i]);
                dao.remover(sabor.getSaborID());
                listaExcluir.add(sabor);
            }
            for(Sabor sabor:listaExcluir){
                saborTableModel.removeSabor(sabor);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Erro ao realizar exclusão de clientes.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirSaborActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizzaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizzaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizzaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizzaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizzaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarPizza;
    private javax.swing.JButton btnAtualizarCliente;
    private javax.swing.JButton btnAtualizarPedido;
    private javax.swing.JButton btnCadastrarSabor;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JButton btnExcluirSabor;
    private javax.swing.JButton btnFiltrarCliente;
    private javax.swing.JButton btnInserirCliente;
    private javax.swing.JButton btnInserirPedido;
    private javax.swing.JButton btnLimparCliente;
    private javax.swing.JButton btnLimparSabor;
    private javax.swing.JButton btnListarCliente;
    private javax.swing.JButton btnListarSabor;
    private javax.swing.JButton btnLocar;
    private javax.swing.JButton btnPesqCliente;
    private javax.swing.JComboBox comboSelecionaCliente;
    private javax.swing.JButton confirmaB;
    private javax.swing.JTextField edtNomeCliente;
    private javax.swing.JTextField edtNomeCliente1;
    private javax.swing.JTextField edtNomeCliente2;
    private javax.swing.JTextField edtNomeClientePesq;
    private javax.swing.JFormattedTextField edtPesqCliente;
    private javax.swing.JTextField edtSobrenomeCliente;
    private javax.swing.JTextField edtSobrenomeClientePesq;
    private javax.swing.JFormattedTextField edtTelefoneCliente;
    private javax.swing.JFormattedTextField edtTelefoneClientePesq;
    private javax.swing.JPanel guiaCliente;
    private javax.swing.JPanel guiaPedido;
    private javax.swing.JPanel guiaPreço;
    private javax.swing.JPanel guiaSabores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbCPFClientePesq;
    private javax.swing.JLabel lbNomeCliente;
    private javax.swing.JLabel lbNomeCliente1;
    private javax.swing.JLabel lbNomeClientePesq;
    private javax.swing.JLabel lbPorVeiculo;
    private javax.swing.JLabel lbSelecionarVeiculoVender;
    private javax.swing.JLabel lbSelecioneCliente;
    private javax.swing.JLabel lbSelecioneCliente1;
    private javax.swing.JLabel lbSobrenomeCliente;
    private javax.swing.JLabel lbSobrenomeCliente1;
    private javax.swing.JLabel lbSobrenomeClientePesq;
    private javax.swing.JLabel lbTelefoneCliente;
    private javax.swing.JLabel lbTelefoneCliente1;
    private javax.swing.JPanel painelListarPedidos;
    private javax.swing.JTabbedPane painelPizzaria;
    private javax.swing.JTable tabelaCliente;
    private javax.swing.JTable tabelaPedidos;
    private javax.swing.JTable tabelaSabor;
    private javax.swing.JPanel tiposPizzaP;
    private javax.swing.JTextField valorCmTF;
    // End of variables declaration//GEN-END:variables
}
